Repository Chris-Johnston/Grappel, pull requests merged in 2018-05, with the labels that each got.

#65 Add level where you go up
  385/Assets/Materials/Ground Physics.physicsMaterial2D
  385/Assets/Materials/Ground Physics.physicsMaterial2D.meta
  385/Assets/Materials/SwingUpWall.mat
  385/Assets/Materials/SwingUpWall.mat.meta
  385/Assets/Materials/SwingUpWall.physicsMaterial2D
  385/Assets/Materials/SwingUpWall.physicsMaterial2D.meta
  385/Assets/Materials/Water.mat
  385/Assets/Materials/Water.mat.meta
  385/Assets/Prefabs/GrapplePoint.prefab
  385/Assets/Prefabs/Player 1.prefab
  385/Assets/Scenes/Level1.unity
  385/Assets/Scenes/Menu.unity
  385/Assets/Scenes/SwingUp.unity
  385/Assets/Scenes/SwingUp.unity.meta
  385/Assets/Scenes/Tutorial.unity
  385/Assets/Scripts/SwingUp.meta
  385/Assets/Scripts/SwingUp/SwingUpController.cs
  385/Assets/Scripts/SwingUp/SwingUpController.cs.meta
  385/Assets/Scripts/SwingUp/WaterWarnController.cs
  385/Assets/Scripts/SwingUp/WaterWarnController.cs.meta
  385/Assets/Sprites/GrappleHook.png
  385/Assets/Sprites/Materials.meta
  385/Assets/Sprites/Materials/water rising.mat
  385/Assets/Sprites/Materials/water rising.mat.meta
  385/Assets/Sprites/main menu background.png
  385/Assets/Sprites/main menu background.png.meta
  385/Assets/Sprites/main menu background.xcf
  385/Assets/Sprites/main menu background.xcf.meta
  385/Assets/Sprites/water rising.png
  385/Assets/Sprites/water rising.png.meta
  385/Assets/Sprites/water rising.xcf
  385/Assets/Sprites/water rising.xcf.meta
  385/Assets/Sprites/youloseui.png
  385/Assets/Sprites/youloseui.png.meta
  385/ProjectSettings/EditorBuildSettings.asset
  385/ProjectSettings/EditorSettings.asset
Labels: enhancement

#71 Level 1 and Tutorial Design Cleanup
  385/Assets/Scenes/Level1.unity
  385/Assets/Scenes/Tutorial.unity
Labels: enhancement

#72 Added skeleton Level2 bouncy theme
  385/Assets/Materials/Bounce.mat
  385/Assets/Materials/Bounce.mat.meta
  385/Assets/Materials/Bounce.physicsMaterial2D
  385/Assets/Materials/Bounce.physicsMaterial2D.meta
  385/Assets/Scenes/Level2.meta
  385/Assets/Scenes/Level2.unity
  385/Assets/Scenes/Level2.unity.meta
  385/Assets/Scenes/Level2/LightingData.asset
  385/Assets/Scenes/Level2/LightingData.asset.meta
  385/Assets/Scenes/Level2/ReflectionProbe-0.exr
  385/Assets/Scenes/Level2/ReflectionProbe-0.exr.meta
  385/ProjectSettings/PresetManager.asset
  385/ProjectSettings/ProjectVersion.txt
  385/UnityPackageManager/manifest.json
Labels: enhancement

#78 Added dynamic camera level1 level2
  385/Assets/Materials/Invisible.mat
  385/Assets/Materials/Invisible.mat.meta
  385/Assets/Prefabs/GrapplePoint.prefab
  385/Assets/Scenes/Level1.unity
  385/Assets/Scenes/Level2.unity
  385/Assets/Scenes/Menu.unity
  385/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement, question

#79 Fix #76, changed the rappeling axis
  385/ProjectSettings/InputManager.asset
Labels: enhancement

#90 Make the player be a cube to be visually cohesive
  385/Assets/Materials/Player1.mat
  385/Assets/Materials/Player1.mat.meta
  385/Assets/Prefabs/Player 1.prefab
Labels: Art And Polish

#86 Disappearing Platforms
  385/Assets/Prefabs/DissapearingPlatform.prefab
  385/Assets/Prefabs/DissapearingPlatform.prefab.meta
  385/Assets/Scenes/TestPlatform.unity
  385/Assets/Scenes/TestPlatform.unity.meta
  385/Assets/Scripts/PlayerController.cs
  385/Assets/Scripts/Tags.cs
  385/ProjectSettings/TagManager.asset
Labels: enhancement

#89 Add support for UnityEvents for common player actions.
  385/Assets/Prefabs/GrapplePoint.prefab
  385/Assets/Scenes/GrappleThrow.unity
  385/Assets/Scripts/DebugPrinter.cs
  385/Assets/Scripts/DebugPrinter.cs.meta
  385/Assets/Scripts/GrapplePointController.cs
  385/Assets/Scripts/GrapplePointController.cs.meta
  385/Assets/Scripts/PlayerController.cs
  385/Assets/Scripts/RopeSystem.cs
  385/Assets/Scripts/SwingUp/SwingUpController.cs
Labels: enhancement

#95 Fix misc codefactor issues
  385/Assets/Scripts/GameControl.cs
  385/Assets/Scripts/KillTrigger.cs
  385/Assets/Scripts/PlayerCamera.cs
  385/Assets/Scripts/RopeSystem.cs
  385/Assets/Scripts/Tags.cs
  385/Assets/Scripts/WinLoseController.cs
Labels: Low Priority

#94 Fix controller firing when in the deadzone
  385/Assets/Scripts/PlayerController.cs
  385/Assets/Scripts/RopeSystem.cs
Labels: Needs Review, bug, enhancement

#98 Fix #74, Add crumbling grapple points
  385/Assets/Prefabs/CrumblePoint.prefab
  385/Assets/Prefabs/CrumblePoint.prefab.meta
  385/Assets/Scenes/GrappleThrow.unity
  385/Assets/Scripts/CrumblingGrapplePointController.cs
  385/Assets/Scripts/CrumblingGrapplePointController.cs.meta
  385/Assets/Scripts/RopeSystem.cs
  385/Assets/Sprites/CrumblePoint.png
  385/Assets/Sprites/CrumblePoint.png.meta
Labels: WIP, enhancement

#99 Fix #80 Prevent rope over extension
  385/Assets/Prefabs/Player 1.prefab
  385/Assets/Scenes/GrappleThrow.unity
  385/Assets/Scripts/RopeSystem.cs
Labels: bug

#96 Add Tutorial Scene that demonstrates mechanics for player one at a time
  385/Assets/Materials/TutorialFinal.meta
  385/Assets/Materials/TutorialFinal/LightingData.asset
  385/Assets/Materials/TutorialFinal/LightingData.asset.meta
  385/Assets/Materials/TutorialFinal/ReflectionProbe-0.exr
  385/Assets/Materials/TutorialFinal/ReflectionProbe-0.exr.meta
  385/Assets/Scenes/Level1.unity
  385/Assets/Scenes/Level2.unity
  385/Assets/Scenes/Menu.unity
  385/Assets/Scenes/TutorialFinal.unity
  385/Assets/Scenes/TutorialFinal.unity.meta
  385/ProjectSettings/EditorBuildSettings.asset
Labels: WIP, enhancement

#105 Music/SFX/Control Icons
  385/Assets/Music&SFX/hipdrums.wav
  385/Assets/Music&SFX/hipdrums.wav.meta
  385/Assets/Music&SFX/hippyyeet.wav
  385/Assets/Music&SFX/hippyyeet.wav.meta
  385/Assets/Music&SFX/jump1.wav
  385/Assets/Music&SFX/jump1.wav.meta
  385/Assets/Music&SFX/jump3.wav
  385/Assets/Music&SFX/jump3.wav.meta
  385/Assets/Music&SFX/land1.wav
  385/Assets/Music&SFX/land1.wav.meta
  385/Assets/Music&SFX/land2.wav
  385/Assets/Music&SFX/land2.wav.meta
  385/Assets/Prefabs/GrapplePoint.prefab
  385/Assets/Prefabs/Music3.prefab
  385/Assets/Prefabs/Music3.prefab.meta
  385/Assets/Prefabs/Player 1.prefab
  385/Assets/Prefabs/PlayerJump.prefab
  385/Assets/Prefabs/PlayerJump.prefab.meta
  385/Assets/Scenes/Level1.unity
  385/Assets/Scenes/Level2.unity
  385/Assets/Scenes/Menu.unity
  385/Assets/Scenes/SwingUp.unity
  385/Assets/Scenes/TutorialFinal.unity
  385/Assets/Sprites/Abutton.png
  385/Assets/Sprites/Abutton.png.meta
  385/Assets/Sprites/DDpad.png
  385/Assets/Sprites/DDpad.png.meta
  385/Assets/Sprites/LDpad.png
  385/Assets/Sprites/LDpad.png.meta
  385/Assets/Sprites/RAnalog.png
  385/Assets/Sprites/RAnalog.png.meta
  385/Assets/Sprites/RDpad.png
  385/Assets/Sprites/RDpad.png.meta
  385/Assets/Sprites/RTrigger.png
  385/Assets/Sprites/RTrigger.png.meta
  385/Assets/Sprites/UDpad.png
  385/Assets/Sprites/UDpad.png.meta
Labels: Art And Polish

#106 Level0
  385/Assets/Materials/Level0.meta
  385/Assets/Materials/Level0/LightingData.asset
  385/Assets/Materials/Level0/LightingData.asset.meta
  385/Assets/Materials/Level0/ReflectionProbe-0.exr
  385/Assets/Materials/Level0/ReflectionProbe-0.exr.meta
  385/Assets/Scenes/Level0.unity
  385/Assets/Scenes/Level0.unity.meta
  385/Assets/Scenes/Menu.unity
  385/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#108 Final tutorial level
  385/Assets/Materials/RealFinalTutorial.meta
  385/Assets/Materials/RealFinalTutorial/LightingData.asset
  385/Assets/Materials/RealFinalTutorial/LightingData.asset.meta
  385/Assets/Materials/RealFinalTutorial/ReflectionProbe-0.exr
  385/Assets/Materials/RealFinalTutorial/ReflectionProbe-0.exr.meta
  385/Assets/Prefabs/BouncyPlatform.prefab
  385/Assets/Prefabs/BouncyPlatform.prefab.meta
  385/Assets/Prefabs/GrapplePoint.prefab
  385/Assets/Prefabs/key_sprite.prefab
  385/Assets/Prefabs/key_sprite.prefab.meta
  385/Assets/Scenes/Menu.unity
  385/Assets/Scenes/RealFinalTutorial.unity
  385/Assets/Scenes/RealFinalTutorial.unity.meta
  385/Assets/Sprites/instruction_images.meta
  385/Assets/Sprites/instruction_images/Abutton.png
  385/Assets/Sprites/instruction_images/Abutton.png.meta
  385/Assets/Sprites/instruction_images/DDpad.png
  385/Assets/Sprites/instruction_images/DDpad.png.meta
  385/Assets/Sprites/instruction_images/LDpad.png
  385/Assets/Sprites/instruction_images/LDpad.png.meta
  385/Assets/Sprites/instruction_images/RAnalog.png
  385/Assets/Sprites/instruction_images/RAnalog.png.meta
  385/Assets/Sprites/instruction_images/RDpad.png
  385/Assets/Sprites/instruction_images/RDpad.png.meta
  385/Assets/Sprites/instruction_images/RTrigger.png
  385/Assets/Sprites/instruction_images/RTrigger.png.meta
  385/Assets/Sprites/instruction_images/UDpad.png
  385/Assets/Sprites/instruction_images/UDpad.png.meta
  385/Assets/Sprites/instruction_images/arrow-right.png
  385/Assets/Sprites/instruction_images/arrow-right.png.meta
  385/Assets/Sprites/instruction_images/danger_text.png
  385/Assets/Sprites/instruction_images/danger_text.png.meta
  385/Assets/Sprites/instruction_images/grapple_text.png
  385/Assets/Sprites/instruction_images/grapple_text.png.meta
  385/Assets/Sprites/instruction_images/hold_text.png
  385/Assets/Sprites/instruction_images/hold_text.png.meta
  385/Assets/Sprites/instruction_images/jump_text.png
  385/Assets/Sprites/instruction_images/jump_text.png.meta
  385/Assets/Sprites/instruction_images/move_text.png
  385/Assets/Sprites/instruction_images/move_text.png.meta
  385/Assets/Sprites/instruction_images/rappel_text.png
  385/Assets/Sprites/instruction_images/rappel_text.png.meta
  385/Assets/Sprites/instruction_images/swing_text.png
  385/Assets/Sprites/instruction_images/swing_text.png.meta
  385/Assets/Sprites/instruction_images/trans_a.png
  385/Assets/Sprites/instruction_images/trans_a.png.meta
  385/Assets/Sprites/instruction_images/trans_click.png
  385/Assets/Sprites/instruction_images/trans_click.png.meta
  385/Assets/Sprites/instruction_images/trans_d.png
  385/Assets/Sprites/instruction_images/trans_d.png.meta
  385/Assets/Sprites/instruction_images/trans_s.png
  385/Assets/Sprites/instruction_images/trans_s.png.meta
  385/Assets/Sprites/instruction_images/trans_space.png
  385/Assets/Sprites/instruction_images/trans_space.png.meta
  385/Assets/Sprites/instruction_images/trans_w.png
  385/Assets/Sprites/instruction_images/trans_w.png.meta
  385/Assets/Sprites/instruction_images/win_texxt.png
  385/Assets/Sprites/instruction_images/win_texxt.png.meta
  385/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement
